name: Pulumi

on:
  push:

jobs:

  preview:
    name: Pulumi Preview
    runs-on: ubuntu-latest
    environment: dev
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ vars.AWS_REGION }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ env.AWS_REGION }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ env.AWS_SESSION_TOKEN }}

      - name: Install requirements
        run: pip install -r requirements.txt
        working-directory: pulumi

      - name: Applying infrastructure 🚀
        run: |
          pulumi login s3://pulumi-lab-state2
          pulumi stack select dev
          pulumi preview
        working-directory: pulumi

      # - name: Applying infrastructure 🚀
      #   uses: pulumi/actions@v4
      #   with:
      #     command: preview
      #     stack-name: test-deployment/dev
      #     cloud-url: s3://pulumi-lab-state2

