name: Pulumi

on:
  push:

jobs:

  preview:
    name: Pulumi Preview
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ vars.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - run: pip install -r requirements.txt
        working-directory: pulumi

      - name: Applying infrastructure 🚀
        uses: pulumi/actions@v4
        with:
          command: preview
          stack-name: dev
          cloud-url: s3://pulumi-lab-state2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}
